#logging:
#  level:
#    ROOT: DEBUG

spring:
  profiles:
    active: dev

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: Password@123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update


